vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Apr 2007 17:53:07 -0000
vti_extenderversion:SR|4.0.2.8912
vti_cacheddtm:TX|22 Apr 2007 17:53:07 -0000
vti_filesize:IR|13381
vti_cachedlinkinfo:VX|S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif H|main.asp S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif H|add.asp S|../im/clear.gif H|view.asp S|../im/clear.gif H|categories_add.asp S|../im/clear.gif H|categories.asp S|../im/clear.gif S|../im/clear.gif S|../clear.gif H|settings.asp S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif H|logout.asp S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif A|add3.asp H|javascript:open_Event_Name(); H|javascript:open_Event_Date(); H|javascript:open_Event_Time(); H|javascript:open_Event_Date(); H|javascript:open_Event_Time(); H|javascript:open_Event_Category(); H|javascript:open_Event_Location(); H|javascript:open_Event_Description(); S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif
vti_cachedsvcrellinks:VX|NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif FHUS|calendar/admin/main.asp NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif FHUS|calendar/Admin/add.asp NSUS|calendar/im/clear.gif FHUS|calendar/admin/view.asp NSUS|calendar/im/clear.gif FHUS|calendar/admin/categories_add.asp NSUS|calendar/im/clear.gif FHUS|calendar/admin/categories.asp NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/clear.gif FHUS|calendar/admin/settings.asp NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif FHUS|calendar/admin/logout.asp NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif FAUS|calendar/admin/add3.asp SHUS|javascript:open_Event_Name(); SHUS|javascript:open_Event_Date(); SHUS|javascript:open_Event_Time(); SHUS|javascript:open_Event_Date(); SHUS|javascript:open_Event_Time(); SHUS|javascript:open_Event_Category(); SHUS|javascript:open_Event_Location(); SHUS|javascript:open_Event_Description(); NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif
vti_cachedtitle:SR|Micro Men Ltd Builders & Handymen Calendar
vti_title:SR|Micro Men Ltd Builders & Handymen Calendar
vti_cachedbodystyle:SR|<body bgcolor="#F0F0F0" vlink="#48576C" link="#48576C" alink="#000000">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_backlinkinfo:VX|calendar/admin/categories_add2.asp calendar/admin/add3.asp calendar/admin/categories_add.asp calendar/admin/delete.asp calendar/admin/view.asp calendar/admin/categories.asp calendar/admin/categories_delete.asp calendar/admin/edit.asp calendar/admin/main.asp calendar/admin/add.asp calendar/admin/add2.asp calendar/admin/add3b.asp calendar/admin/edit2.asp calendar/admin/settings.asp calendar/admin/settings2.asp
