vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|21 Apr 2007 22:31:47 -0000
vti_extenderversion:SR|4.0.2.8912
vti_cacheddtm:TX|21 Apr 2007 22:31:47 -0000
vti_filesize:IR|26107
vti_cachedlinkinfo:VX|S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif H|main.asp S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif H|add.asp S|../im/clear.gif H|view.asp S|../im/clear.gif H|categories_add.asp S|../im/clear.gif H|categories.asp S|../im/clear.gif S|../im/clear.gif S|../clear.gif H|settings.asp S|../im/clear.gif H|http://scripts.ocean12tech.com/asp/calendar/support/ S|../im/clear.gif H|http://scripts.ocean12tech.com/asp/calendar/docs/ S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif H|logout.asp S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif A|settings2.asp H|javascript:open_Settings_Admin_ID(); S|../im/clear.gif H|javascript:open_Settings_Abbreviate_Days(); H|javascript:open_Settings_Abbreviate_Months(); H|javascript:open_Settings_Event_Display(); S|../im/clear.gif H|javascript:open_Settings_Page_Title(); H|javascript:open_Settings_Background_Color(); H|javascript:open_Settings_Font_Color(); H|javascript:open_Settings_Link_Color(); H|javascript:open_Settings_Hover_Link_Color(); H|javascript:open_Settings_Visited_Link_Color(); H|javascript:open_Settings_Active_Link_Color(); S|../im/clear.gif H|javascript:open_Settings_Weekday_Font(); H|javascript:open_Settings_Weekday_Font_Size(); H|javascript:open_Settings_Weekday_Font_Color(); H|javascript:open_Settings_Weekday_Background_Color(); S|../im/clear.gif H|javascript:open_Settings_Date_Font(); H|javascript:open_Settings_Date_Font_Size(); H|javascript:open_Settings_Date_Font_Color(); H|javascript:open_Settings_Date_Background_Color(); S|../im/clear.gif H|javascript:open_Settings_Event_Font(); H|javascript:open_Settings_Event_Font_Size(); H|javascript:open_Settings_Event_Font_Color(); S|../im/clear.gif H|javascript:open_Settings_Cell_Background_Color(); H|javascript:open_Settings_Cell_Width(); H|javascript:open_Settings_Cell_Height(); H|javascript:open_Settings_Border_Size(); H|javascript:open_Settings_Border_Color(); S|../im/clear.gif H|javascript:open_Settings_Header(); H|javascript:open_Settings_Footer(); S|../im/clear.gif H|javascript:open_Settings_Password(); S|../im/clear.gif S|../im/clear.gif S|../im/clear.gif H|http://scripts.ocean12tech.com H|http://scripts.ocean12tech.com S|../im/clear.gif S|../im/clear.gif
vti_cachedsvcrellinks:VX|NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif FHUS|calendar/Admin/main.asp NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif FHUS|calendar/Admin/add.asp NSUS|calendar/im/clear.gif FHUS|calendar/admin/view.asp NSUS|calendar/im/clear.gif FHUS|calendar/Admin/categories_add.asp NSUS|calendar/im/clear.gif FHUS|calendar/Admin/categories.asp NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/clear.gif FHUS|calendar/Admin/settings.asp NSUS|calendar/im/clear.gif NHHS|http://scripts.ocean12tech.com/asp/calendar/support/ NSUS|calendar/im/clear.gif NHHS|http://scripts.ocean12tech.com/asp/calendar/docs/ NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif FHUS|calendar/admin/logout.asp NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif FAUS|calendar/admin/settings2.asp SHUS|javascript:open_Settings_Admin_ID(); NSUS|calendar/im/clear.gif SHUS|javascript:open_Settings_Abbreviate_Days(); SHUS|javascript:open_Settings_Abbreviate_Months(); SHUS|javascript:open_Settings_Event_Display(); NSUS|calendar/im/clear.gif SHUS|javascript:open_Settings_Page_Title(); SHUS|javascript:open_Settings_Background_Color(); SHUS|javascript:open_Settings_Font_Color(); SHUS|javascript:open_Settings_Link_Color(); SHUS|javascript:open_Settings_Hover_Link_Color(); SHUS|javascript:open_Settings_Visited_Link_Color(); SHUS|javascript:open_Settings_Active_Link_Color(); NSUS|calendar/im/clear.gif SHUS|javascript:open_Settings_Weekday_Font(); SHUS|javascript:open_Settings_Weekday_Font_Size(); SHUS|javascript:open_Settings_Weekday_Font_Color(); SHUS|javascript:open_Settings_Weekday_Background_Color(); NSUS|calendar/im/clear.gif SHUS|javascript:open_Settings_Date_Font(); SHUS|javascript:open_Settings_Date_Font_Size(); SHUS|javascript:open_Settings_Date_Font_Color(); SHUS|javascript:open_Settings_Date_Background_Color(); NSUS|calendar/im/clear.gif SHUS|javascript:open_Settings_Event_Font(); SHUS|javascript:open_Settings_Event_Font_Size(); SHUS|javascript:open_Settings_Event_Font_Color(); NSUS|calendar/im/clear.gif SHUS|javascript:open_Settings_Cell_Background_Color(); SHUS|javascript:open_Settings_Cell_Width(); SHUS|javascript:open_Settings_Cell_Height(); SHUS|javascript:open_Settings_Border_Size(); SHUS|javascript:open_Settings_Border_Color(); NSUS|calendar/im/clear.gif SHUS|javascript:open_Settings_Header(); SHUS|javascript:open_Settings_Footer(); NSUS|calendar/im/clear.gif SHUS|javascript:open_Settings_Password(); NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif NHHS|http://scripts.ocean12tech.com NHHS|http://scripts.ocean12tech.com NSUS|calendar/im/clear.gif NSUS|calendar/im/clear.gif
vti_cachedtitle:SR|Ocean12 ASP Calendar Manager
vti_title:SR|Ocean12 ASP Calendar Manager
vti_cachedbodystyle:SR|<body bgcolor="#F0F0F0" vlink="#48576C" link="#48576C" alink="#000000">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_backlinkinfo:VX|calendar/admin/categories_add2.asp calendar/admin/add3.asp calendar/admin/categories_add.asp calendar/admin/delete.asp calendar/admin/view.asp calendar/admin/categories.asp calendar/admin/categories_delete.asp calendar/admin/edit.asp calendar/admin/main.asp calendar/admin/add.asp calendar/admin/add2.asp calendar/admin/add3b.asp calendar/admin/edit2.asp calendar/admin/settings.asp calendar/admin/settings2.asp
